In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
import time
import pymatching
import json



In [9]:
s_mat = [[1,1,0,0],[0,1,1,0],[0,0,0,1]]
weights = [0.4]*4
matching_x = pymatching.Matching(s_mat,spacelike_weights=weights)

syndrome_x = [1,0,0]
recovery_x = matching_x.decode(syndrome_x)
print(recovery_x)

syndrome_x = [1,1,0]
recovery_x = matching_x.decode(syndrome_x)
print(recovery_x)

syndrome_x = [0,0,1]
recovery_x = matching_x.decode(syndrome_x)
print(recovery_x)

[1 0 0 0]
[0 1 0 0]
[0 0 0 1]
